[build]
  command = "npm run build"
  publish = "dist"

# Optional: speed up installs
[build.environment]
  NODE_VERSION = "18"

# Optional: if you use client-side routing in the future
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
